# TODO: FIX COMPOSE, NOT WORKING CURRENTLY

services:

  backend:
    container_name: fastify_next_server_cont
    build:
      context: ./apps/api
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    environment:
      - PORT=80
      - POSTGRES_DB_PSW=${POSTGRES_DB_PSW}
      - POSTGRES_DB_HOST=${POSTGRES_DB_HOST}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - POSTGRES_USER_NAME=${POSTGRES_USER_NAME}
      - JWT_SECRET=${JWT_SECRET}
    develop:
      watch:
        - action: sync
          path: ./apps/api
          target: /apps/api
          ignore:
            - node_modules/
            - dist/

  frontend:
    container_name: fastify_next_client_cont
    build:
      context: ./apps/web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:80
      - API_INTERNAL_URL=http://backend:80
      - NEXT_TELEMETRY_DISABLED=1
    develop:
      watch:
        - action: sync
          path: ./apps/web
          target: /apps/web
          ignore:
            - node_modules/
            - .next

  postgres:
    container_name: fastify_next_postgres_cont
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_DB_PSW}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER_NAME}
    ports:
      - "5432:5432"

  # pgadmin:
  #   container_name: fastify_next_pgadmin_cont
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=
  #     - PGADMIN_DEFAULT_PASSWORD=
  #   ports:
  #     - "5050:80"